# frozen_string_literal: true

require "minitest/autorun"
require "fileutils"
require "tmpdir"
require "rails/generators"
require_relative "scenarios"
require_relative "../../lib/generators/authnz_eleven/authnz_eleven_generator"

module AuthnzEleven
  # Sibling to ScenarioCompletenessTest:
  # that one guarantees every *template* is built by some scenario; this one
  # guarantees every emitted *controller flow* has a behavioral test built
  # alongside it — the net that catches "a user edits a generated controller,
  # breaks it, and the generated suite stays green because nothing tested it."
  #
  # Every controller template on disk must be classified exactly once as:
  #   COVERAGE   — a behavioral test template exercises it, and (asserted below)
  #                every scenario that builds the controller also builds that test.
  #   KNOWN_GAPS — a flow we intend to cover but haven't yet. The living to-do
  #                list; the goal is to burn it down to empty. Listed here so the
  #                gap is *visible*, not silent.
  #   SKIP       — deliberately not behavior-tested, with a reason (infra exercised
  #                indirectly, dev-only shortcuts, WebAuthn ceremonies that need a
  #                virtual authenticator).
  #
  # A newly added controller that fits none of the three fails the test: you must
  # write a test (COVERAGE), record the debt (KNOWN_GAPS), or justify the skip
  # (SKIP). That's what stops the behavioral gap from silently regrowing.
  class BehavioralCoverageTest < Minitest::Test
    TEMPLATES_ROOT = File.expand_path("../../lib/generators/authnz_eleven/templates", __dir__)
    DUMMY_APP_ROOT = File.expand_path("../dummy", __dir__)
    SKELETON = %w[Gemfile app bin config db lib Rakefile].freeze

    # controller template => the behavioral test template that exercises it. The
    # co-emission assertion below proves the mapped test is generated by every
    # scenario that generates the controller — so the coverage can't drift.
    COVERAGE = {
      "controllers/users/sessions_controller.rb.tt" =>
        "test_unit/controllers/users/sessions_controller_test.rb.tt",
      "controllers/users/passkeys/sessions_controller.rb.tt" =>
        "test_unit/controllers/passkey_ceremony_test.rb.tt",
      "controllers/settings/passkeys_controller.rb.tt" =>
        "test_unit/controllers/passkey_ceremony_test.rb.tt",
      "controllers/users/multi_factor_authentication/challenge/security_keys_controller.rb.tt" =>
        "test_unit/controllers/security_key_ceremony_test.rb.tt",
      "controllers/settings/multi_factor_authentication/security_keys_controller.rb.tt" =>
        "test_unit/controllers/security_key_ceremony_test.rb.tt",
      "controllers/users/omniauth/registrations_controller.rb.tt" =>
        "test_unit/controllers/users/omniauth/registrations_controller_test.rb.tt",
      "controllers/settings/omniauth_identities_controller.rb.tt" =>
        "test_unit/controllers/settings/omniauth_identities_controller_test.rb.tt",
      "controllers/users/credential_enrollments_controller.rb.tt" =>
        "test_unit/controllers/credential_enrollment_test.rb.tt",
      "controllers/users/credential_enrollments/passwords_controller.rb.tt" =>
        "test_unit/controllers/credential_enrollment_test.rb.tt",
      "controllers/users/credential_enrollments/passkeys_controller.rb.tt" =>
        "test_unit/controllers/credential_enrollment_test.rb.tt",
      "controllers/users/registrations_controller.rb.tt" =>
        "test_unit/controllers/users/registrations_controller_test.rb.tt",
      "controllers/users/password_resets_controller.rb.tt" =>
        "test_unit/controllers/users/password_resets_controller_test.rb.tt",
      "controllers/users/magic_link_controller.rb.tt" =>
        "test_unit/controllers/users/magic_link_controller_test.rb.tt",
      "controllers/users/sudos_controller.rb.tt" =>
        "test_unit/controllers/users/sudos_controller_test.rb.tt",
      # One test drives the whole self-service settings area.
      "controllers/settings/dashboard_controller.rb.tt" =>
        "test_unit/controllers/settings/management_test.rb.tt",
      "controllers/settings/sessions_controller.rb.tt" =>
        "test_unit/controllers/settings/management_test.rb.tt",
      "controllers/settings/api_tokens_controller.rb.tt" =>
        "test_unit/controllers/settings/api_tokens_controller_test.rb.tt",
      "controllers/settings/users_controller.rb.tt" =>
        "test_unit/controllers/settings/management_test.rb.tt",
      "controllers/settings/passwords_controller.rb.tt" =>
        "test_unit/controllers/settings/management_test.rb.tt",
      "controllers/settings/emails_controller.rb.tt" =>
        "test_unit/controllers/settings/management_test.rb.tt",
      "controllers/settings/phones_controller.rb.tt" =>
        "test_unit/controllers/settings/management_test.rb.tt",
      "controllers/settings/email_verifications_controller.rb.tt" =>
        "test_unit/controllers/settings/email_verifications_controller_test.rb.tt",
      "controllers/users/email_verifications_controller.rb.tt" =>
        "test_unit/controllers/users/email_verifications_controller_test.rb.tt",
      "controllers/users/registrations/email_verifications_controller.rb.tt" =>
        "test_unit/controllers/users/registrations/email_verifications_controller_test.rb.tt",
      "controllers/settings/phone_verifications_controller.rb.tt" =>
        "test_unit/controllers/settings/phone_verifications_controller_test.rb.tt",
      "controllers/users/registrations/phone_verifications_controller.rb.tt" =>
        "test_unit/controllers/users/registrations/phone_verifications_controller_test.rb.tt",
      "controllers/users/sms_sessions_controller.rb.tt" =>
        "test_unit/controllers/users/sms_sessions_controller_test.rb.tt",
      "controllers/invitations_controller.rb.tt" =>
        "test_unit/controllers/invitations_controller_test.rb.tt",
      "controllers/settings/invitations_controller.rb.tt" =>
        "test_unit/controllers/settings/invitations_controller_test.rb.tt",
      "controllers/settings/authentications/events_controller.rb.tt" =>
        "test_unit/controllers/settings/authentications/events_controller_test.rb.tt",
      "controllers/users/omniauth_controller.rb.tt" =>
        "test_unit/controllers/users/omniauth_controller_test.rb.tt",
      "controllers/teams_controller.rb.tt" =>
        "test_unit/controllers/teams_controller_test.rb.tt",
      "controllers/active_teams_controller.rb.tt" =>
        "test_unit/controllers/teams_controller_test.rb.tt",
      # The typed second-factor challenges are driven by one test.
      "controllers/users/multi_factor_authentication/challenge/totps_controller.rb.tt" =>
        "test_unit/controllers/users/multi_factor_authentication/challenge_test.rb.tt",
      "controllers/users/multi_factor_authentication/challenge/recovery_codes_controller.rb.tt" =>
        "test_unit/controllers/users/multi_factor_authentication/challenge_test.rb.tt",
      "controllers/users/multi_factor_authentication/challenge/sms_controller.rb.tt" =>
        "test_unit/controllers/users/multi_factor_authentication/challenge_test.rb.tt",
      # Settings-area MFA management (enroll authenticator or SMS + recovery codes).
      "controllers/settings/multi_factor_authentication/authenticators_controller.rb.tt" =>
        "test_unit/controllers/settings/multi_factor_authentication/management_test.rb.tt",
      "controllers/settings/multi_factor_authentication/recovery_codes_controller.rb.tt" =>
        "test_unit/controllers/settings/multi_factor_authentication/management_test.rb.tt",
      "controllers/settings/multi_factor_authentication/sms_controller.rb.tt" =>
        "test_unit/controllers/settings/multi_factor_authentication/management_test.rb.tt",
      # One test proves the whole admin area is not found (admins_only → 404).
      "controllers/admin/dashboard_controller.rb.tt" =>
        "test_unit/controllers/admin/access_test.rb.tt",
      "controllers/admin/users_controller.rb.tt" =>
        "test_unit/controllers/admin/access_test.rb.tt",
      "controllers/admin/sessions_controller.rb.tt" =>
        "test_unit/controllers/admin/access_test.rb.tt",
      # Lives outside the admin area (it has to), but it's the same flow.
      "controllers/impersonations_controller.rb.tt" =>
        "test_unit/controllers/admin/access_test.rb.tt",
      # Admin-forced MFA enrollment + recovery-code rotation.
      "controllers/admin/multi_factor_authentication/authenticators_controller.rb.tt" =>
        "test_unit/controllers/admin/multi_factor_authentication_test.rb.tt",
      "controllers/admin/multi_factor_authentication/recovery_codes_controller.rb.tt" =>
        "test_unit/controllers/admin/multi_factor_authentication_test.rb.tt"
    }.freeze

    # Emitted flows with no behavioral test yet — the debt ledger. Empty: every
    # generated controller flow now has starter behavioral coverage. Add an entry here
    # (rather than leaving a controller unclassified) if a future flow lands
    # before its test does. Each key must match a real, still-uncovered template.
    KNOWN_GAPS = {}.freeze

    # Deliberately not behavior-tested. Keys are path prefixes; each must match at
    # least one template (staleness guard below).
    SKIP = {
      "controllers/concerns/" =>
        "controller concerns (authentication/authorization/captchable/easy_dev_login/sudoable) are " \
        "exercised indirectly by every controller test that runs behind them — sudoable's require_sudo " \
        "guard specifically by users/sudos_controller_test, which drives a really-guarded action",
      "controllers/base_controller.rb.tt" =>
        "a namespaced identity's base controller is wiring; its behavior surfaces " \
        "through that identity's own controller tests",
      "controllers/admin_controller.rb.tt" =>
        "abstract superclass for the Admin::* controllers; the behavior lives in the subclasses",
      "controllers/settings_controller.rb.tt" =>
        "abstract superclass for the Settings::* controllers; the behavior lives in the subclasses",
      "controllers/users/easy_dev_logins_controller.rb.tt" =>
        "development-only 'sign in as anyone' shortcut, not production behavior"
    }.freeze

    def all_controller_templates
      Dir.glob(File.join(TEMPLATES_ROOT, "controllers", "**", "*.tt"))
         .map { |p| p.sub("#{TEMPLATES_ROOT}/", "") }
    end

    # Every controller template lands in exactly one bucket. An unclassified one
    # (a newly added controller nobody triaged) fails here — the regrowth guard.
    def test_every_controller_is_classified
      classified = COVERAGE.keys.to_set | KNOWN_GAPS.keys.to_set

      all_controller_templates.each do |tmpl|
        in_named = classified.include?(tmpl)
        in_skip = SKIP.keys.any? { |prefix| tmpl.start_with?(prefix) }

        assert in_named || in_skip,
               "Controller template is not classified for behavioral coverage:\n  #{tmpl}\n" \
               "Add it to COVERAGE (with a test), KNOWN_GAPS (record the debt), or SKIP (with a reason)."
        refute(in_named && in_skip,
               "Controller template is both named and SKIP-matched — pick one:\n  #{tmpl}")
      end
    end

    # The core guarantee: whenever a build emits a covered controller, it also
    # emits that controller's test. So "generate feature X" always yields "test
    # for feature X" — the coverage can't silently detach. Enforced for every
    # identity in every scenario (namespaced ones included — each renders on its own,
    # a valid single-identity build) by rendering each invocation alone.
    def test_covered_controllers_ship_their_test
      Scenarios::ALL.each do |name, invocations|
        invocations.each do |flags|
          built = render_and_record(name, [flags])
          COVERAGE.each do |controller, test|
            next unless built.include?(controller)

            assert_includes built, test,
                            "#{name.inspect} (#{flags.join(" ")}) builds #{controller} but not #{test}. " \
                            "Wire the test into AuthnzElevenGenerator#create_tests under the controller's predicate."
          end
        end
      end
    end

    # A COVERAGE test template must exist on disk (a typo'd path would otherwise
    # make the co-emission check above silently vacuous for un-built scenarios).
    def test_coverage_test_templates_exist
      missing = COVERAGE.values.reject { |t| File.exist?(File.join(TEMPLATES_ROOT, t)) }
      assert_empty missing, "COVERAGE maps to test templates that don't exist:\n  #{missing.join("\n  ")}"
    end

    # KNOWN_GAPS keys must be real, currently-uncovered controllers — so the ledger
    # can't carry a stale entry (renamed away) or one already moved into COVERAGE.
    def test_known_gaps_are_real_and_uncovered
      stale = KNOWN_GAPS.keys.reject { |k| File.exist?(File.join(TEMPLATES_ROOT, k)) }
      assert_empty stale, "KNOWN_GAPS names templates that don't exist (remove them):\n  #{stale.join("\n  ")}"

      moved = KNOWN_GAPS.keys & COVERAGE.keys
      assert_empty moved,
                   "In both KNOWN_GAPS and COVERAGE — drop the stale gap entry:\n  #{moved.join("\n  ")}"
    end

    # Every SKIP prefix must still match a template — a dead prefix (renamed dir)
    # is misleading. Mirrors ScenarioCompletenessTest's staleness guard.
    def test_skip_prefixes_are_live
      dead = SKIP.keys.reject { |prefix| all_controller_templates.any? { |t| t.start_with?(prefix) } }
      assert_empty dead, "These SKIP prefixes match no controller template (remove them):\n  #{dead.join("\n  ")}"
    end

    private

    def render_and_record(name, invocations)
      recorded = []
      Dir.mktmpdir("coverage_#{name}") do |dir|
        SKELETON.each do |entry|
          src = File.join(DUMMY_APP_ROOT, entry)
          FileUtils.cp_r(src, File.join(dir, entry)) if File.exist?(src)
        end
        recorder = recorder_module(recorded)
        invocations.each do |flags|
          gen = AuthnzElevenGenerator.new([], flags)
          gen.destination_root = dir
          gen.singleton_class.prepend(recorder)
          silence { gen.invoke_all }
        end
      end
      recorded.select { |s| s.end_with?(".tt") }.to_set
    end

    def recorder_module(sink)
      Module.new do
        define_method(:template) do |source, *rest, &blk|
          sink << source.to_s
          super(source, *rest, &blk)
        end
        define_method(:migration_template) do |source, *rest, &blk|
          sink << source.to_s
          super(source, *rest, &blk)
        end
        define_method(:copy_file) do |source, *rest, &blk|
          sink << source.to_s
          super(source, *rest, &blk)
        end
        define_method(:run) { |*_args, **_opts| nil }
      end
    end

    def silence
      original = $stdout
      $stdout = File.open(File::NULL, "w")
      yield
    ensure
      $stdout.close
      $stdout = original
    end
  end
end
