# frozen_string_literal: true

require_relative "generator_test_case"
require_relative "../../lib/authnz_eleven/version"

module AuthnzEleven
  # The provenance comment at the top of the initializer: the gem version and an
  # equivalent invocation, so an app can say years later what it was built from.
  class GenerationStampTest < GeneratorTestCase
    INITIALIZER = "config/initializers/authentication.rb"

    def test_stamps_the_version_and_the_flags_that_were_given
      run_generator %w[--password --trackable --second-factor=totp --email]

      assert_file INITIALIZER do |contents|
        assert_match "# Generated by authnz_eleven #{AuthnzEleven::VERSION} with:", contents
        assert_match "bin/rails generate authnz_eleven", contents
        assert_match "--email=required", contents
        assert_match "--trackable", contents
        assert_match "--second-factor=totp", contents
        refute_match(/--registration/, contents)
        refute_match(/--verifiable/, contents)
      end
    end

    def test_names_a_flag_turned_off_but_not_one_left_at_its_default
      run_generator %w[--password --no-contactable --email]

      assert_file INITIALIZER do |contents|
        assert_match "--no-contactable", contents
        refute_match(/--trackable/, contents)
      end
    end

    def test_wraps_a_long_invocation_with_shell_continuations
      run_generator %w[--password --trackable --sudoable --bannable --registration=open-and-invites
                       --admin-dashboard --impersonatable --rememberable --timeoutable --email]

      assert_file INITIALIZER do |contents|
        stamp = contents.lines.take_while { |line| line.start_with?("#") }.join
        assert_match(/\\\n#     --/, stamp)
      end
    end
  end
end
